spring:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/inshorts"
    username: root
    password: chisom123

server:
  error:
    include-message: always

