spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/inshorts"
    username: root
    password: chisom123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-message: always

